### PR TITLE
Support for http basic auth

### PR DESCRIPTION
**Pull request by DirkLachowski**
@leojh Coming back to the auth header(s) proposed by you i've added support for basic auth. As long as the endpoint is only reachable by https this should be sufficient.

### CODE REVIEW

**Comment by leojh** [comment]
@DirkLachowski can you look at the merge conflict here?

**Comment by DirkLachowski** [comment]
@leojh fixed conflict

**Comment by leojh** [comment]
Merged, sorry I didn't see your notification until now for some reason.

**Comment by DirkLachowski** [comment]
No worries. Any chance you could push a fresh version to npmjs?

**Comment by leojh** [comment]
Done, it's version 0.0.9

**Comment by DirkLachowski** [comment]
Perfect, thanks.

**Pull request merged**
